services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    volumes:
      - ./uploads:/app/uploads
      - ./chroma_db:/app/chroma_db
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8001

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./uploads:/app/uploads
    environment:
      - BACKEND_URL=http://backend:8001
    command: streamlit run frontend.py